#1 calculate expected proportions of heterozygotes from real data
ex.prop<-function(rs,method=c("fisher","chi.sq")){
  n<-unlist(c(rs[4]))
  p<-(rs[1]+rs[2]/2)/n
  ob<-unlist(c(rs[1:3]))
  eX<-unlist(c((p^2) * n,2*p*(1-p) * n,((1-p)^2) * n))
  delta <- rs[2]-(2*p*(1-p) * n)
  stat<-match.arg(method)
  pval<-switch(stat,fisher=suppressWarnings(fisher.test(cbind(ob,eX),workspace = 2e8))$p.value,chi.sq=suppressWarnings(chisq.test(cbind(ob,eX)))$p.value)
  return(c(eX/n,pval,delta))
}

#' Identify significantly different heterozygotes from SNPs data
#'
#' This function will recognize the SNPs that are significantly different from the expected under HWE and plot potential duplicated snps
#'
#' @param d.info duplication info table generated from filtered vcfs using the function dup.snp.info
#' @param method character. Method for testing significance. Fisher exact test ("fisher") or Chi squre test ("chi.sq")
#' @param plot logical. Whether to plot the identified duplicated snps with the expected values
#' @param verbose logical, if TRUE, the progress is shown
#' @param ... other arguments passed to plot
#'
#' @return A matrix of expected heterozygote proportions from the observed data with p-value indicating significantly deviating snps, thus duplicates.
#' If enabled, the function also plots the recognized duplicates in red and expected (singletons) in black on a prop. of homozygote alt Vs. prop. of heterozygote plot
#' p2 observed homozygote reference
#' het expected
#'
#' @author Piyal Karunarathne, Pascal Milesi
#'
#' @examples
#' data(hets)
#' d.info <- dup.snp.info(het.table=hets,normalize=FALSE)
#' duplicates<-sig.hets(d.info,plot=TRUE)
#'
#' @importFrom grDevices col2rgb rgb
#' @importFrom stats fisher.test median quantile rbinom sd smooth.spline chisq.test
#' @importFrom utils setTxtProgressBar txtProgressBar
#' @importFrom colorspace rainbow_hcl
#' @export
sig.hets<-function(d.info,method=c("fisher","chi.sq"),plot=TRUE,verbose=TRUE,...){
  d<-d.info[,c("NHomRef","NHet","NHomAlt","Nsamp")]
  colnames(d)<-c("h1","het","h2","truNsample")
  method<-match.arg(method)
  if(verbose){
    message("assessing excess of heterozygotes")
    df<-data.frame(t(apply_pb(d,1,ex.prop,method=method)))
  } else {
    df<-data.frame(t(apply(d,1,ex.prop,method=method)))
  }
  colnames(df)<-c("p2","het","q2","pval","delta")
  df$dup.stats<-"singleton";df$dup.stats[which(df$pval < 0.05 & df$delta > 0 )]<-"duplicated"
  if(plot){
    l<-list(...)
    if(is.null(l$cex)) l$cex=0.2
    if(is.null(l$pch)) l$pch=19
    if(is.null(l$xlim)) l$xlim=c(0,1)
    if(is.null(l$ylim)) l$ylim=c(0,1)
    if(is.null(l$col)) cols<-makeTransparent(rainbow_hcl(2),alpha=0.3) else cols<-makeTransparent(l$col,alpha=0.3)

    d$Color <- cols[1]
    d$Color [which(df$dup.stats=="duplicated")]<- cols[2]#& df$delta > 0
    plot(d.info$propHet~d.info$propHomAlt, pch=l$pch, cex=l$cex,col=d$Color,xlim=l$xlim,ylim=l$ylim,
         xlab="Proportion of Alternate Homozygotes",ylab="Proportion of Heterozygotes")
    lines((smm<-smooth.spline(df$het~df$q2)),col="blue")
    legend("bottomright", c("singleton","duplicate","expected"), col = c(cols,"blue"), lty = c(0, 0, 1), lwd = c(0, 0, 1),pch = c(l$pch, l$pch, NA),
           cex = 0.8,inset=c(0,1), xpd=TRUE, horiz=TRUE, bty="n")
  }
  return(data.frame(cbind(d.info[,c(1:3)],df[,c(4:6)]),row.names = NULL))
}


#' Detect duplicated snps from depth of coverage and number of heterozygotes
#'
#' This function will determine if a snp is duplicated or singleton based on the number of heterozygotes present for that specific snps and the median depth of coverage for the allele.
#' @param d.info a data.frame of duplication info generated by dup.snp.info function
#' @param stringency character. Confidence interval to be used in filtering duplicates
#' @param plot logical. whether to plot the duplicated and singleton snps
#' @param ... other arguments passed to plot
#' @param rat ratio med/median
#'
#' @return a dataframe of snps with their status of duplication. If plot=TRUE, plot depicting duplicated and non-duplicated (singleton) alleles
#'
#' @author Piyal Karunarathne
#'
#' @examples
#' data(hets)
#' d.info <- dup.snp.info(het.table=hets,normalize=FALSE)
#' duplicated<-sig.snps(d.info,stringency="max")
#'
#' @export
sig.snps<-function(d.info,stringency=c("95","99","max"),rat=c("median","mean"),plot=TRUE,...){
  rat<-match.arg(rat)
  sts<-apply_pb(d.info,1,dupsvd,stringency=match.arg(stringency),rat=rat)
  d<-cbind(d.info[,c(1:4,10:12)],dup.stat=sts)
  d$dup.stat[d.info$NoRareAllele<2*0.01*0.99*d.info$truNsample]<-"low MAF"
  d$dup.stat[d.info$MedCovHet<=5]<-"low coverage"
  if(plot){
    dup.plot(d,...)
  }
  return(d[,-9])
}

#' Detect and plot duplicated snps
#'
#' This function uses excess of heterozygotes under HWE depth of coverage vs. no. of heterozygotes dependent expected allele ratios to determine the duplicated snps from singletons.
#' @param d.info a data.frame of duplication info generated by dup.snp.info function
#' @param stringency character. Confidence interval to be used in filtering duplicates
#' @param plot logical. If proportion of heterozygotes vs. allele median ratio should be plotted to visualize the detected duplicates
#' @param ... other arguments passed to plot
#' @param rat ratio med/median
#' @param method haracter. Method for testing significance. Fisher exact test ("fisher") or Chi squre test ("chi.sq")
#'
#' @return a data frame of snps categorized into duplicates and singletons along with allele median ratio and heterozygote and homozygote proportions.
#'
#' @author Piyal Karunarathne
#'
#' @examples
#' data(hets)
#' d.info <- dup.snp.info(het.table=hets,normalize=FALSE)
#' duplicated<-dup.detect(d.info,stringency="max",plot=TRUE)
#'
#' @export
dup.detect<-function(d.info,stringency=c("95","99","max"),rat=c("median","mean"),method=c("fisher","chi.sq"),plot=TRUE,...){
  rat<-match.arg(rat)
  method<-match.arg(method)
  message("Assessing excess of heterozygotes")
  d2<-sig.hets(d.info,plot=FALSE,method=method)
  message("Assessing snp deviates")
  ds<-sig.snps(d.info,stringency=match.arg(stringency),rat=rat,plot=FALSE)
  ds$dup.stat[d2$dup.stats=="duplicated"]<-"duplicated"
  if(plot){
    dup.plot(ds,...)
  }
  return(ds)
}



#' Plot duplicates
#'
#' The function plots detected duplicates from functions "sig.snps", and "dup.detect"
#'
#' @param ds a data frame of detected duplicates
#' @param ... other graphical parameters to be passed to the function plot
#'
#' @importFrom colorspace rainbow_hcl
#'
#' @return plots duplicates on proportion of heterozygotes vs allele median ratio
#'
#' @author Piyal Karunarathne
#'
#' @examples
#' data(hets)
#' d.info <- dup.snp.info(het.table=hets,normalize=FALSE)
#' duplicated<-dup.detect(d.info,stringency="max",plot=FALSE)
#' dup.plot(duplicated)
#'
#' @export
dup.plot<-function(ds,...){
  l<-list(...)
  if(is.null(l$cex)) l$cex=0.2
  if(is.null(l$pch)) l$pch=19
  if(is.null(l$xlim)) l$xlim=c(0,1)
  if(is.null(l$ylim)) l$ylim=c(0,1)
  if(is.null(l$alpha)) l$alpha=0.3
  if(is.null(l$col)) cols<-makeTransparent(c("black",rainbow_hcl(16)[c(16,10,7)]),alpha=l$alpha) else cols<-makeTransparent(l$col,alpha = l$alpha)
  ds$Color <- cols[1]
  ds$Color [ds$dup.stat=="duplicated"]<- cols[2]
  ds$Color [ds$dup.stat=="low MAF"]<- cols[3]
  ds$Color [ds$dup.stat=="low coverage"]<- cols[4]
  plot(ds$MedRatio~ds$PropHet, pch=l$pch, cex=l$cex,col=ds$Color,xlim=l$xlim,ylim=l$ylim,frame=F,
       ylab="Allele Median Ratio",xlab="Proportion of Heterozygotes")
  legend("bottomright", c("singleton","duplicate","low MAF","low coverage"), col = makeTransparent(cols,alpha=1), pch=l$pch,
         cex = 0.8,inset=c(0,1), xpd=TRUE, horiz=TRUE, bty="n")

}


#' Detect duplicates from SNPs
#'
#'
#'
#'
#' @export
dupGet<-function(data,test=c("z.het","z.05","z.all","chi.het","chi.05","chi.all"),intersection=FALSE,method=c("fisher","chi.sq"),plot=TRUE,verbose=TRUE,...){
  #data check
  data<-as.data.frame(data)
  if(!any(colnames(data)=="propHet")){
    stop("please provide the data with the output of allele.info()")
  } else {
    ht<-sig.hets(data,plot=F,verbose=verbose)
    test<-match.arg(test,several.ok = TRUE)
    if(length(test)==6){
      pp<-data[,c("z.all","chi.all")]
    } else {
      pp<-data.frame(data[,test])
    }
    if(intersection){
      df<-matrix(NA,nrow = nrow(pp),ncol = ncol(pp))
      for(i in 1:ncol(pp)){
        df[which(pp[,i]<0.05/nrow(pp)),i]<-1
      }
      pp$dup.stat<-"singleton"
      pp$dup.stat[which(rowSums(df)==(ncol(pp)-1))]<-"duplicated"
    } else {
      pp$dup.stat<-"singleton"
      for(i in 1:ncol(pp)){
        pp$dup.stat[pp[,i]<0.05/nrow(pp)]<-"duplicated"
      }
    }
    pp$dup.stat[which(ht$dup.stats=="duplicated")]<-"duplicated"
    pp<-data.frame(data[,1:10],dup.stat=pp$dup.stat)

    if(plot){
      l<-list(...)
      if(is.null(l$cex)) l$cex=0.2
      if(is.null(l$pch)) l$pch=19
      if(is.null(l$xlim)) l$xlim=c(0,1)
      if(is.null(l$ylim)) l$ylim=c(0,1)
      if(is.null(l$alpha)) l$alpha=0.3
      #if(is.null(l$col)) p.list$col<-makeTransparent(c(colorspace::heat_hcl(12,h=c(0,-100),c=c(40,80),l=c(75,40),power=1)[10],
                                                              #colorspace::terrain_hcl(12,c=c(65,0),l=c(45,90),power=c(1/2,1.5))[2]))
      if(is.null(l$col)) p.list$col<-makeTransparent(c("tomato",colorspace::terrain_hcl(12,c=c(65,0),l=c(45,90),power=c(1/2,1.5))[2]))
      Color <- rep(p.list$col[2],nrow(pp))
      Color[pp$dup.stat=="duplicated"]<- p.list$col[1]
      plot(pp$medRatio~pp$propHet, pch=l$pch, cex=l$cex,col=Color,xlim=l$xlim,ylim=l$ylim,frame=F,
           ylab="Allele Median Ratio",xlab="Proportion of Heterozygotes")
      legend("bottomright", c("duplicate","singleton"), col = makeTransparent(p.list$col,alpha=1), pch=l$pch,
             cex = 0.8,inset=c(0,1), xpd=TRUE, horiz=TRUE, bty="n")
    }
  }
  return(pp)
}







