#1 calculate expected proportions of heterozygotes from real data
ex.prop<-function(rs,method=c("fisher","chi.sq")){
  n<-unlist(c(rs[4]))
  p<-(rs[1]+rs[2]/2)/n
  ob<-unlist(c(rs[1:3]))
  eX<-unlist(c((p^2) * n,2*p*(1-p) * n,((1-p)^2) * n))
  delta <- rs[2]-(2*p*(1-p) * n)
  stat<-match.arg(method)
  pval<-switch(stat,fisher=suppressWarnings(fisher.test(cbind(ob,eX)))$p.value,chi.sq=suppressWarnings(chisq.test(cbind(ob,eX)))$p.value)
  return(c(eX/n,pval,delta))
}

#' Identify significantly different heterozygotes from SNPs data
#'
#' This function will recognize the SNPs that are significantly different from the expected under HWE and plot potential duplicated snps
#'
#' @param d.info duplication info table generated from filtered vcfs using the function dup.snp.info
#' @param method character. Method for testing significance. Fisher exact test ("fisher") or Chi squre test ("chi.sq")
#' @param plot logical. Whether to plot the identified duplicated snps with the expected values
#' @param ... other arguments passed to plot
#'
#' @return A matrix of expected heterozygote proportions from the observed data with p-value indicating significantly deviating snps, thus duplicates.
#' If enabled, the function also plots the recognized duplicates in red and expected (singletons) in black on a prop. of homozygote alt Vs. prop. of heterozygote plot
#' p2 observed homozygote reference
#' het expected
#'
#' @author Piyal Karunarathne, Pascal Milesi
#'
#' @examples
#' data(hets)
#' d.info <- dup.snp.info(het.table=hets,normalize=FALSE)
#' duplicates<-sig.hets(d.info,plot=TRUE)
#'
#' @importFrom grDevices col2rgb rgb
#' @importFrom stats fisher.test median quantile rbinom sd smooth.spline chisq.test
#' @importFrom utils setTxtProgressBar txtProgressBar
#' @export
sig.hets<-function(d.info,method=c("fisher","chi.sq"),plot=TRUE,...){
  d<-d.info[,c("NHomFreq","NumHet","NHomRare","truNsample")]
  colnames(d)<-c("h1","het","h2","truNsample")
  method<-match.arg(method)
  df<-data.frame(t(apply_pb(d,1,ex.prop,method=method)))
  colnames(df)<-c("p2","het","q2","pval","delta")
  df$dup.stats<-"singleton";df$dup.stats[which(df$pval < 0.05 & df$delta > 0 )]<-"duplicated"
  if(plot){
    cols<-makeTransparent(c("black","red"),alpha=0.2)
    d$Color <- cols[1]
    d$Color [which(df$dup.stats=="duplicated")]<- cols[2]#& df$delta > 0
    l<-list(...)
    if(is.null(l$cex)) l$cex=0.2
    if(is.null(l$pch)) l$pch=19
    if(is.null(l$xlim)) l$xlim=c(0,1)
    if(is.null(l$ylim)) l$ylim=c(0,1)
    plot(d.info$PropHet~d.info$PropHomRare, pch=l$pch, cex=l$cex,col=d$Color,xlim=l$xlim,ylim=l$ylim,
         xlab="Proportion of Alternate Homozygotes",ylab="Proportion of Heterozygotes")
    lines((smm<-smooth.spline(df$het~df$q2)),col="blue")
  }
  return(data.frame(cbind(d.info[,c(1:4,10:12)],df[,c(4:6)])))
}

#' Detect duplicated snps from depth of coverage and number of heterozygotes
#'
#' This function will determine if a snp is duplicated or singleton based on the number of heterozygotes present for that specific snps and the median depth of coverage for the allele.
#' @param d.info a data.frame of duplication info generated by dup.snp.info function
#' @param stringency character. Confidence interval to be used in filtering duplicates
#' @param plot logical. whether to plot the duplicated and singleton snps
#' @param ... other arguments passed to plot
#'
#' @return a dataframe of snps with their status of duplication. If plot=TRUE, plot depicting duplicated and non-duplicated (singleton) alleles
#'
#' @author Piyal Karunarathne
#'
#' @examples
#' data(hets)
#' d.info <- dup.snp.info(het.table=hets,normalize=FALSE)
#' duplicated<-sig.snps(d.info,stringency="max")
#'
#' @export
sig.snps<-function(d.info,stringency=c("95","99","max"),plot=TRUE,...){
  sts<-apply_pb(d.info,1,dupsvd,stringency=match.arg(stringency))
  d<-cbind(d.info[,c(1:4,10:12)],dup.stat=sts)
  d$dup.stat[d.info$NoRareAllele<2*0.01*0.99*d.info$truNsample]<-"low MAF"
  d$dup.stat[d.info$MedCovHet<=5]<-"low coverage"
  if(plot){
    cols<-makeTransparent(c("black","red","cyan","magenta"),alpha=0.2)
    d$Color <- cols[1]
    d$Color [d$dup.stat=="duplicated"]<- cols[2]
    d$Color [d$dup.stat=="low MAF"]<- cols[3]
    d$Color [d$dup.stat=="low coverage"]<- cols[4]
    l<-list(...)
    if(is.null(l$cex)) l$cex=0.2
    if(is.null(l$pch)) l$pch=19
    if(is.null(l$xlim)) l$xlim=c(0,1)
    if(is.null(l$ylim)) l$ylim=c(0,1)
    plot(d$MedRatio~d$PropHet, pch=l$pch, cex=l$cex,col=d$Color,xlim=l$xlim,ylim=l$ylim,
         ylab="Allele Median Ratio",xlab="Proportion of Heterozygotes")
  }
  return(d[,-9])
}

#' Detect and plot duplicated snps
#'
#' This function uses excess of heterozygotes under HWE depth of coverage vs. no. of heterozygotes dependent expected allele ratios to determine the duplicated snps from singletons.
#' @param d.info a data.frame of duplication info generated by dup.snp.info function
#' @param stringency character. Confidence interval to be used in filtering duplicates
#' @param plot logical. If proportion of heterozygotes vs. allele median ratio should be plotted to visualize the detected duplicates
#' @param ... other arguments passed to plot
#'
#' @return a data frame of snps categorized into duplicates and singletons along with allele median ratio and heterozygote and homozygote proportions.
#'
#' @author Piyal Karunarathne
#'
#' @examples
#' data(hets)
#' d.info <- dup.snp.info(het.table=hets,normalize=FALSE)
#' duplicated<-dup.detect(d.info,stringency="max",plot=TRUE)
#'
#' @export
dup.detect<-function(d.info,stringency=c("95","99","max"),plot=TRUE,...){
  message("Assessing excess of heterozygotes")
  d2<-sig.hets(d.info,plot=FALSE)
  message("Assessing snp deviates")
  ds<-sig.snps(d.info,stringency=match.arg(stringency),plot=FALSE)
  ds$dup.stat[d2$dup.stats=="duplicated"]<-"duplicated"
  if(plot){
    cols<-makeTransparent(c("black","red","cyan","magenta"),alpha=0.2)
    ds$Color <- cols[1]
    ds$Color [ds$dup.stat=="duplicated"]<- cols[2]
    ds$Color [ds$dup.stat=="low MAF"]<- cols[3]
    ds$Color [ds$dup.stat=="low coverage"]<- cols[4]
    l<-list(...)
    if(is.null(l$cex)) l$cex=0.2
    if(is.null(l$pch)) l$pch=19
    if(is.null(l$xlim)) l$xlim=c(0,1)
    if(is.null(l$ylim)) l$ylim=c(0,1)
    plot(ds$MedRatio~ds$PropHet, pch=l$pch, cex=l$cex,col=ds$Color,xlim=l$xlim,ylim=l$ylim,
         ylab="Allele Median Ratio",xlab="Proportion of Heterozygotes")
  }
  return(ds)
}


