# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

process_snp <- function(X, AD) {
    .Call('_rCNV_process_snp', PACKAGE = 'rCNV', X, AD)
}

process_column1 <- function(column, info_type, max_adn, ind_adn) {
    .Call('_rCNV_process_column1', PACKAGE = 'rCNV', column, info_type, max_adn, ind_adn)
}

